language: python
python:
  - "2.7"
  - "3.4"
env:

  - DJANGO=1.8
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO
  - pip install -q coverage
  - pip install -e .
script:
  - coverage run --source changuito setup.py test
