language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q git://github.com/angvp/django-changuito.git#egg=django-changuito
  - pip install -q nose --use-mirrors
  - pip install -q django-nose --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python runtests.py
