language: python
sudo: false
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.7"
  - DJANGO="Django<1.6"
install:
  - pip install -q $DJANGO
  - pip install -q coverage
  - pip install -e .
script:
  - coverage run --source changuito setup.py test
