language: python
python:
  - "2.7"
  - "3.4"
env:

  - Django<1.9
  - Django<1.8
  - Django<1.7
  - Django<1.6
install:
  - pip install -q $DJANGO
  - pip install -q coverage
  - pip install -e .
script:
  - coverage run --source changuito setup.py test
