language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5.1
  - DJANGO=1.5.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q nose --use-mirrors
  - pip install -q django-nose --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python runtests.py
