language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO
  - pip install -q coverage
  - pip install -e .
script:
  - if [ $TRAVIS_PYTHON_VERSION == '2.6' ] && [ $DJANGO == '1.7' ]; then return 0; else coverage run --source oml setup.py test; fi
